### get wallets data
POST http://localhost:5000/dashboard/wallet/getWallets
Content-Type: application/json

{
    "name": "lam2"
}

### add a wallet
POST http://localhost:5000/dashboard/wallet/addwallet
Content-Type: application/json

{
    "name": "lam",
    "wallet": {
        "walletName": "vi dien tu",
        "balance": 2310
    }
}

### update a wallet
POST http://localhost:5000/dashboard/wallet/updateWallet
Content-Type: application/json

{
    "name": "lam",
    "walletId": 1,
    "newWallet": {
        "newWalletName": "so cuc ki do",
        "newBalance": 5500
    }
}

### delete a wallet
POST http://localhost:5000/dashboard/wallet/deleteWallet
Content-Type: application/json

{
    "name": "lam2",
    "walletId": 1
}

### add a trade
POST http://localhost:5000/dashboard/trade/addTrade
Content-Type: application/json

{
    "name": "lam",
    "walletId": 1,
    "trade": {
        "reciveType": "other",
        "amount": 15,
        "decription": "123"
    }
}

### update a trade

POST http://localhost:5000/dashboard/trade/updateTrade
Content-Type: application/json

{
    "name": "Lam",
    "walletId": 1,
    "tradeId": "6132d262810fb361beabd28e",
    "trade": {
        "newDay": 12,
        "newMonth": 12,
        "newReciveType": "other",
        "newAmount": 1234,
        "newDecription": "yeah"
    }
}

### delete a trade
POST http://localhost:5000/dashboard/trade/deleteTrade
Content-Type: application/json

{
    "name": "lam",
    "walletId": 1,
    "tradeId": "613975c4e499d6d756a7cf6c"
}